### ISSUE TITLE
Pypi

### ISSUE THREAD

**Issue by ghost** [XavierTolza/PyGithubRepoDeleter#1]
Why Don't You push it to Pypi?

**Comment by XavierTolza** [comment]
Because laziness ;)
And not that much users

**Comment by ghost** [comment]
So Can I Push to Pypi With Your Permission

**Comment by XavierTolza** [comment]
Sure!
Could you also document it in the readme?

**Comment by XavierTolza** [comment]
I added you as a collaborator. Feel free to push it to pypi, document/automate it or whatever

**Comment by ghost** [comment]
Yes Sure
